# Dockerignore para apps/web-hsk/Dockerfile.

.git
.github
.husky

node_modules
**/node_modules
**/.next
**/dist
**/build
**/.turbo
**/.nest
**/coverage
**/*.tsbuildinfo

apps/api
apps/web-fo

.vscode
.idea
.devcontainer
docker-compose.yml

.env
.env.*
!.env.example
yarn.lock
package-lock.json

*.md
!README.md
docs
RUNBOOK.md

**/*.spec.ts
**/*.e2e-spec.ts
**/test
**/tests

*.log
.DS_Store
